# Generated by Django 3.2.14 on 2023-02-22 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=50)),
                ('feature_addon', models.CharField(default='None', max_length=30)),
                ('module_addon', models.CharField(default='None', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astercrm.software')),
                ('usage_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usage_user', 'usage_software')},
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_smno', models.IntegerField(unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('price', models.IntegerField(default=1000)),
                ('last_login', models.CharField(default='None', max_length=30)),
                ('status', models.CharField(default='Active', max_length=15)),
                ('usage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astercrm.usage')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('sales_type', models.CharField(max_length=30)),
                ('plant_smno', models.IntegerField(unique=True)),
                ('usage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astercrm.usage')),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('support_type', models.CharField(max_length=30)),
                ('remark', models.CharField(max_length=130)),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astercrm.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='User_addon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileno', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=40)),
                ('job_title', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('discount', models.IntegerField()),
                ('role', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'company_name')},
            },
        ),
    ]
