# Generated by Django 3.2.14 on 2023-02-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astercrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='plant_smno',
            field=models.IntegerField(max_length=15, unique=True),
        ),
    ]
