# Generated by Django 3.2.14 on 2023-02-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=50)),
                ('feature_addon', models.CharField(default='None', max_length=30)),
                ('module_addon', models.CharField(default='None', max_length=30)),
            ],
        ),
    ]
