# Generated by Django 3.2.14 on 2023-02-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
